FROM node:lts-alpine

# env variables
ENV VUE_APP_API_SERVER=http://192.168.56.103:8181
ENV VUE_APP_BRIDGE_SERVER=http://192.168.56.103:5005

# install simple http server for serving static content
RUN npm install -g http-server

# make the 'app' folder the current working directory
WORKDIR /app

# copy both 'package.json' and 'package-lock.json' (if available)
COPY package*.json ./

# install project dependencies
RUN npm install

# copy project files and folders to the current working directory (i.e. 'app' folder)
COPY . .

# build app for production with minification
RUN npm run build

EXPOSE 80
CMD [ "http-server", "dist", "-p", "80" ]
