export const REGISTER_SOURCE = "REGISTER_SOURCE";
export const DELETE_SOURCE = "DELETE_SOURCE";
export const SOCKET_RETRIEVE_SOURCES = "SOCKET_RETRIEVE_SOURCES";
export const SOCKET_UPDATE_SOURCE = "SOCKET_UPDATE_SOURCE";